### ISSUE TITLE
500 Error when not login

### ISSUE THREAD

**Issue by sambrown03** [VertisanPRO/PterodactylRegisterInstaller#1]
Getting a 500 error when someone tried to view a services on https://domain.com**/store/view/29** if not login, when they login this issue doesn't present itself? would there be a way to redirect the user to a login or register page if this is clicked when not login?

![Uploading 500error.png…]()

**Comment by PadowYT2** [comment]
You are in a completly wrong repository, please refer to our Discord Server - https://discord.gg/RJfCxC2W3e
